#!/usr/bin/env bash
# Configure nginx to listen on port 80
pkill nginx
sed -i 's/listen 80 default_server;/listen 80;/' /etc/nginx/sites-available/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
nginx
