#!/bin/bash

# List files in current directory in long format (including hidden)
ls -la

# List files in parent directory in long format (including hidden)
ls -la ../

# List files in /boot directory in long format (including hidden)
ls -la /boot
