#!/usr/bin/env bash
# Script that configures an Ubuntu server by changing localhost and facebook.com DNS resolution

# Make a copy of the original hosts file
cp /etc/hosts ~/hosts.new

# Replace/add localhost resolution to 127.0.0.2
sed -i 's/^127\.0\.0\.1[[:space:]]*localhost/127.0.0.2 localhost/' ~/hosts.new

# Replace/add facebook.com resolution to 8.8.8.8
if grep -q "facebook.com" ~/hosts.new; then
    sed -i 's/.*facebook\.com/8.8.8.8 facebook.com/' ~/hosts.new
else
    echo "8.8.8.8 facebook.com" >> ~/hosts.new
fi

# Copy the modified file back to /etc/hosts
cp -f ~/hosts.new /etc/hosts
